### ISSUE TITLE
Issue with getting Dependencies

### ISSUE THREAD

**Issue by jbrychka** [sushilks/alexaHarmonyApp#1]
I could be doing this wrong but when I run npm install, I get errors:
npm ERR! Failed at the node-stringprep@0.6.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-stringprep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system: node-gyp rebuild

It couldn't find PYTHON at first so I ended up installing that and I got a little further but now it's complaining of missing .NET dependencies.

Since you mentioned that the only pre-requisite was Node.js, I'm thinking I maybe doing something wrong.  I'm running this on Windows 7.

Would appreciate your help.
Jim

**Comment by sushilks** [comment]
I haven't see this problem and I am on Linux machine. (I dont have access to windows development env)
Installing node modules requires python and C compiles, It's possible there may be some dependencies missing for the node module.
Try installing the packet independently "npm install node-stringprep" 
Post back your finding.

**Comment by jbrychka** [comment]
Yes, it does look like a Windows issue.  I ended up having to download modules independently. The one that was the main cause, I ended up using the following syntax to make it work:
npm install node-gyp --msvs_version=2010.

Thanks for putting this together. My hub arrives tomorrow and hopefully it will work. :)

**Comment by sushilks** [comment]
Glad you are able to resolve it. 
Ping back if you have any problems getting it to work with your hub.

**Comment by jbrychka** [comment]
Well, I hit a brick wall.  The skill could be found if I ran it in aws
Lambda but when I changed it to my ip, it couldn't find it.  I forwarded
the 443 port too.

So then I just tried to test it using the Alexa Tester (
https://localhost/remote).  I got further but when I tried to call an
intent I got this error:

C:\Alexa\alexaHarmonyApp-master>node server.js
Listening on port 443
Launching the application
Turning on Music Mode!
C:\Alexa\alexaHarmonyApp-master\node_modules\harmony-hub-util\node_modules\harmo
nyhubjs-client\lib\login\hub.js:63
                        if(response.identity && response.identity !==
undefined)
 {
                                   ^
TypeError: Cannot read property 'identity' of undefined
    at Client.<anonymous>
(C:\Alexa\alexaHarmonyApp-master\node_modules\harmony-
hub-util\node_modules\harmonyhubjs-client\lib\login\hub.js:63:15)
    at Client.emit (events.js:107:17)
    at Client.onStanza
(C:\Alexa\alexaHarmonyApp-master\node_modules\harmony-hub
-util\node_modules\harmonyhubjs-client\node_modules\node-xmpp-client\index.js:23
1:14)
    at Connection.emit (events.js:107:17)
    at Connection.onStanza
(C:\Alexa\alexaHarmonyApp-master\node_modules\harmony
-hub-util\node_modules\harmonyhubjs-client\node_modules\node-xmpp-core\lib\Conne
ction.js:370:14)
    at StreamParser.<anonymous>
(C:\Alexa\alexaHarmonyApp-master\node_modules\ha
rmony-hub-util\node_modules\harmonyhubjs-client\node_modules\node-xmpp-core\lib\
Connection.js:226:14)
    at StreamParser.emit (events.js:107:17)
    at SaxLtx.<anonymous>
(C:\Alexa\alexaHarmonyApp-master\node_modules\harmony-
hub-util\node_modules\harmonyhubjs-client\node_modules\node-xmpp-core\lib\Stream
Parser.js:56:22)
    at SaxLtx.emit (events.js:107:17)
    at SaxLtx._handleTagOpening
(C:\Alexa\alexaHarmonyApp-master\node_modules\ha
rmony-hub-util\node_modules\harmonyhubjs-client\node_modules\node-xmpp-core\node
_modules\ltx\lib\sax\sax_ltx.js:30:18)
    at SaxLtx.write
(C:\Alexa\alexaHarmonyApp-master\node_modules\harmony-hub-ut
il\node_modules\harmonyhubjs-client\node_modules\node-xmpp-core\node_modules\ltx
\lib\sax\sax_ltx.js:92:26)
    at StreamParser.write
(C:\Alexa\alexaHarmonyApp-master\node_modules\harmony-
hub-util\node_modules\harmonyhubjs-client\node_modules\node-xmpp-core\lib\Stream
Parser.js:125:21)
    at Connection.onData
(C:\Alexa\alexaHarmonyApp-master\node_modules\harmony-h
ub-util\node_modules\harmonyhubjs-client\node_modules\node-xmpp-core\lib\Connect
ion.js:306:21)
    at Socket.emit (events.js:129:20)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)

C:\Alexa\alexaHarmonyApp-master>

Any idea about the above error?  I did have the hub ip in the
remote_conf.js file.

Jim

**Comment by sushilks** [comment]
I would recommend installing the CLI for the harmony hub and making sure that you can talk to the hub and execute the commands with the CLI. After you have verified the commands you can use Alexa to trigger them.
The CLI is a https://github.com/sushilks/harmonyHubCLI
It can auto discover the hub and show you what kind of commands are supported in the HUB.

**Comment by jbrychka** [comment]
Thanks for the suggestion. I'll give that a try.

Jim

**Comment by jbrychka** [comment]
Have you tried to test this using the browser ui? Just curious if you would
have had the same issue.

**Comment by sushilks** [comment]
I have not tried using the browser UI, 
I can give it a shot next week, will be out for the weekend.
It would help if you can describe how you are accessing UI and how you are testing it.

**Comment by jbrychka** [comment]
Not a big deal. I was just curious. I did the https://localhost/remote from
the browser and used the UI on that page to simulate Alexa calls.

**Comment by jbrychka** [comment]
I tried harmonyHubCLIwithout the ip and received the following error:
C:\Alexa\harmonyHubCLI-master>node harmonyHubCLI.js -r activities
Starting hub Discovery
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EACCES
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1139:19)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at ResponseCollector.start
(C:\Alexa\harmonyHubCLI-master\node_modules\harmo
nyhubjs-discover\lib\responseCollector.js:33:5)
    at Explorer.start
(C:\Alexa\harmonyHubCLI-master\node_modules\harmonyhubjs-d
iscover\lib\explorer.js:75:25)
    at discoverHub (C:\Alexa\harmonyHubCLI-master\harmonyHubCLI.js:210:14)
    at Object.<anonymous>
(C:\Alexa\harmonyHubCLI-master\harmonyHubCLI.js:222:5)

```
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
```

However, that did work if I supplied the IP.  Just note that you do have to
use double quotes instead of single quotes when running on the command line
in Windows as in: node harmonyHubCLI.js -l xxx.xxx.x.xxx  -a "Watch a Movie"

One thing I did notice that I didn't see before is that when triggered by
Alexa, it thinks that it's not calling a secured URL.  The card says:  A
connection could not be established to Resource [https:<my external
ip>/remote], Type [HTTP].  I set up a certificate and using port 443 but
I'm using an IP instead of a URL since I currently don't have one.  Do you
think that would be the cause of not recognizing that its HTTPS?

I appreciate you helping me on this.

Jim

**Comment by sushilks** [comment]
It's possible that the hard coded IP address is creating problem with the certificate, I am not an expert on this. But from the error you pointed to it appears that there is a problem in the connection from amazon to your home server. (The self-signed certificate that you created also needs to be added to the skill)

In my case I am pointing to a fully qualified domain name and I used the same domain for the certificate. 
There are several services that are available that will do the DNS from a fully qualified domain to an ip address for you, in the past I have used them. Just search "free dynamic dns" on google you can probably find one that works for you.

Looks like the dynamic discovery of hub is broken on windows, but I am glad it worked when you specified the ip address for the hub.

**Comment by sushilks** [comment]
It took me some time to get the certificates working on my setup as well, In my case my home router was also creating problems. 
You can run wireshark[https://www.wireshark.org/] on your windows machine and look for traffic on port 443 to see if any of the commands are making it to the windows machine. 
This will help rule out any networking problems.

**Comment by sushilks** [comment]
Did you make any more progress on getting this working ?

**Comment by jbrychka** [comment]
No, I took a detour and used the beta waldo skill with IFTTT. I still want
to get back to it at some point but not sure when that will be.

**Comment by sushilks** [comment]
Ok I will close this then, ping back when you are playing with it again.
