### ISSUE TITLE
Quick question about intents and utterances

### ISSUE THREAD

**Issue by mojopong** [sushilks/alexaHarmonyApp#12]
I got it all working perfectly up until the point where I have to go to my ipaddress/remote nothing loads after that and the server does say its listening on port 443.

Is it possible for you to send me the intents and utterances for me to add to my app?

Thanks for everything you've done with this, it's greatly appreciated.

**Comment by sushilks** [comment]
You can get a list of intents/utterances by pointing to the server and loading the page "https://192.168.1.29/remote" on any web browser. 

The intent/utterances are going to be specific to your remote based on what is programmed there and how the code ties into it. 
It would be best to use the CLI to see a list of available commands on your remote (https://github.com/sushilks/harmonyHubCLI)
then you can modify the code to use those commands.

**Comment by mojopong** [comment]
Using the CLI is there a way to set a specific volume? I had the harmony hub control working from the command line but that only gives me option for up and down on volume not setting a specific volume which is what brought me to this skill in the first place. I'm assuming that IP mentioned is your own on your machine and not a standard one for the skill.
Thanks

**Comment by sushilks** [comment]
How the volume is changed is a function of the equipment that you are using. i.e if the equipment supports setting a specific volume then CLI should be able to execute it. 
I haven't see this as an option on TV or on my amplifier. 

Yes the IP is an example you will need to change it to point to your server.

**Comment by mojopong** [comment]
Ok thank you very much for your help.
