### ISSUE TITLE
Error @npm install

### ISSUE THREAD

**Issue by sdn3rd** [sushilks/alexaHarmonyApp#13]
2729 error Error: ENOENT, open '/home/user/tmp/npm-26993-m3tQyIhE/1464393921744-
0.24791822116822004/package/package.json'

Not sure why I am getting this.

**Comment by sushilks** [comment]
It's not related to this project, 
You can google it, looks like others have had this problem.
Here is one ticket I found
https://github.com/npm/npm/issues/3664
