### ISSUE TITLE
Received and invalid applicaiton ID

### ISSUE THREAD

**Issue by sdn3rd** [sushilks/alexaHarmonyApp#14]
Received and invalid applicaiton ID amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe

When using the /remote page to test out intents and utterances.  I have correctly added the application ID from the Alexa Skills Kit page.

**Comment by tcmedia** [comment]
I am dealing with the same problem. My remote_conf.js is edited to have my App Id but when I send a request from the server its trying to go to the invalid app "amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe"
