### ISSUE TITLE
Alexa Tester & Amazon Endpoint

### ISSUE THREAD

**Issue by tcmedia** [sushilks/alexaHarmonyApp#15]
Hello,

Issue A
I have the alexaHarmonyApp installed to a Raspberry Pi currently. When I use the "Alexa Tester" from https://MYRASPBERRYIP/remote; I receive " Received and invalid applicaiton ID amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe "

I have read that other people have not been able to get it to work either.

Issue B
Not really sure what my Endpoint should be in the Amazon Configuration.
https://MYRASPBERRYIP/remote

When I test it in the App center my service response is "The remote endpoint could not be called, or the response it returned was invalid."

**Comment by sushilks** [comment]
A>Does your "remote_conf.js" file have a different application id ? The application ID does look incorrect, its read from the remote_conf.js file so will be good to check there.

B> On amazon side your endpoint should be https://MYRASPBERRYHOSTNAME
I am yet to see it work with IP address, these are restriction that amazon had when alexa was launched. 
There is also the question of certificates that need to be created for https for your hostname.
This part always takes some time/effort to get it to work.

**Comment by tcmedia** [comment]
My remote_conf.js has my correct app id from Amazon. The web service test just sends a bad one for some reason.

I have created all my certs and believe they are in order. I will direct my endpoint to "raspberrypi" because that is the default and I do not have any others on my network. Anything else I should know?

**Comment by sushilks** [comment]
No, that should be it. 
I am not aware of anyone else doing this with raspberrypi so there might be something new here.

**Comment by tcmedia** [comment]
I enabled Bonjour on my raspberry pi to allow https://rasspberrypi.local and set that as my endpoint. 

Alexa now says " I cannot resolve the host name for the requested skill "

I suppose this will take some more tinkering but I feel that I am progressing.

**Comment by sushilks** [comment]
Yes sounds like it, 
Post what you find I would be curious about a successful execution with raspberrypi.

**Comment by destructure00** [comment]
I am having the same invalid application ID error, verified that the application ID is set correctly in the remote_conf.js file. Running node.js on a windows 10 machine. 

**edit fixed - had to stop and restart server.js, working now

**Comment by rgrdnr** [comment]
posted this on another issues comment, but this might help the people on this thread. the amazon app id for the remote page is actually hard coded in the test.ejs file in the /view folder.

editing the JSON on the webpage before submitting doesn't appear to work. as a work around, check out '$scope.templates' json in that file and you can edit all the 'applicationId' values in the templates to match yours. or you can have it grab the value from the remote_conf.js as well

**Comment by sushilks** [comment]
Hi @destructure00 @rgrdnr 
Great work on finding the problem, It's will help others when testing. 

If there is a cleaner way to grab the application id from the configuration file(remote_conf.js) instead of having it hardcoded in the '$scope.templates' it will be great, would appreciate a pull request on this. 
Otherwise we can keep it as part of documentation so folks can manually modify it.

**Comment by sushilks** [comment]
A fix was easy enough, I have pushed it to the latest master. (Also verified it to work)
Feel free to re-open if the problem persists.
