### ISSUE TITLE
Issues controlling Fire TV

### ISSUE THREAD

**Issue by destructure00** [sushilks/alexaHarmonyApp#16]
Commands sent to Fire TV through HarmonyHubCLI and this app work intermittently. My setup is correct and I do not have any issues consistently controlling infrared devices through CLI or through the alexaHarmonyApp. Fire TV commands (I'm just working on Play and Pause at the moment) work intermittently, maybe one out of every 10 times. If I use the actual Harmony remote or app on my phone, the success rate for the first command sent through CLI or alexaHarmonyApp afterward seems to be higher. I have tried controlling through the Current Activity with 'TransportBasic,Pause' as well as through the device with 'Pause' with the same result either way. 

Is this because Fire TV is controlled through the Bluetooth connection rather than an infrared signal? Has anyone found a resolution to this?

**Comment by sushilks** [comment]
This should be fixed in https://github.com/sushilks/harmonyHubCLI/issues/7
Pull request : sushilks/harmonyHubUtil#2

@destructure00  Please verify on your end.

**Comment by destructure00** [comment]
Updated, working correctly. Thank you!

**Comment by sushilks** [comment]
Thanks for testing it out @destructure00
