### ISSUE TITLE
Add support for additional button presses

### ISSUE THREAD

**Issue by chasepeeler** [sushilks/alexaHarmonyApp#18]
Add support for additional button presses such as pause, play, select, etc.

note: I plan to fork this project and work on this.

**Comment by sushilks** [comment]
These should be supported already, I am not sure what exactly your intent is. 
Can you clarify with some details.

**Comment by chasepeeler** [comment]
I currently don't have this up and running, so I can't verify, but I was pretty sure that the only "button press" was mute. It would turn on/off devices and activities (which aren't configurable), and you could define a "meta" activity, which would start an activity and then change to a specified channel - but I don't remember anything that would let you pause. For me, the two biggest use cases are the ability to mute and pause.

**Comment by sushilks** [comment]
The commands are dynamically read back from harmony remote, so any command configured on the remote as available. 
So as you configure the harmony remote with all the devices in your setup these are populated automatically. 
If you use the CLI you can see a full list of commands that are configured on your remote.

**Comment by chasepeeler** [comment]
Okay, well, it didn't appear to be working like that. I'll verify the next time I get it up and working.

Perhaps I don't have things configured in the hub properly? I actually have the harmomy one remote, and recently added on the hub... if you want to close this out, that's fine. When I get it going again, I'll look into this more and see if I can figure out what's going on. If it still appears to be an issue, I can always create another ticket.

**Comment by sushilks** [comment]
Perfect, feel free to open it if you see it when you test it
