### ISSUE TITLE
Error when using server.js

### ISSUE THREAD

**Issue by synack23** [sushilks/alexaHarmonyApp#2]
Hi,  

I am running server.js on my iMac (running El Capitan) and I get the following error.
app_id : 'amzn1.echo-sdk-ams.app.3eef5436-a086-4974-8e48-deef85fccff3'
    ^^^^^^

SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/owner/Desktop/alexaHarmonyApp-master-2/remote.js:5:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/owner/Desktop/alexaHarmonyApp-master-2/server.js:28:11)
    at Module._compile (module.js:434:26)

Help

**Comment by sushilks** [comment]
Can you post the entire content of your "remote_conf.js"

**Comment by synack23** [comment]
module.exports = {
    hub_ip : '192.168.0.20'
    app_id : 'amzn1.echo-sdk-ams.app.3eef5436-a086-4974-8e48-deef85fccff3'
};

**Comment by synack23** [comment]
When I did the nam install I got this:
npm WARN package.json alexa_harmony_hub_app@1.0.0 No repository field.

**Comment by sushilks** [comment]
It's missing a "," after the first field 
Update it to 
module.exports = {
hub_ip : '192.168.0.20',
app_id : 'amzn1.echo-sdk-ams.app.3eef5436-a086-4974-8e48-deef85fccff3'
};

**Comment by synack23** [comment]
I changed the remote_conf.js but i'm getting this error now:
/Users/owner/Desktop/alexaHarmonyApp-master-2/remote_conf.js:3
    hub_ip : ’192.168.0.20’,
             ^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/owner/Desktop/alexaHarmonyApp-master-2/remote.js:5:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/owner/Desktop/alexaHarmonyApp-master-2/server.js:28:11)
    at Module._compile (module.js:434:26)

**Comment by synack23** [comment]
here is the edited remote_conf.js file:

module.exports = {
    hub_ip : ’192.168.0.20’,
    app_id : ’amzn1.echo-sdk-ams.app.3eef5436-a086-4974-8e48-deef85fccff3’,
};

**Comment by sushilks** [comment]
Looks like you added an extra comma on the app_id line, it's possible that can be problem.
Try this:
module.exports = {
hub_ip : ’192.168.0.20’,
app_id : ’amzn1.echo-sdk-ams.app.3eef5436-a086-4974-8e48-deef85fccff3’
};

**Comment by synack23** [comment]
Here is the new error i'm getting

synack23:alexaHarmonyApp-master-2 owner$ node server.js
Listening on port 443
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:443
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1218:19)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at Object.<anonymous> (/Users/owner/Desktop/alexaHarmonyApp-master-2/server.js:50:13)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by sushilks** [comment]
It appears that the operating system is denying access to the application to run on port 443, this is generally the case with linux OS(I am sure mac/windows have similar restrictions). 

In case of linux I would use 'sudo node server.js' to run it as privileged application to work around this problem.

You also have to make sure no other application is using that port otherwise it will still complain. 
On linux you can do that with 'netstat -nlp'

**Comment by synack23** [comment]
Hi,

I was able to get node server.js to run, but when I go to the test page I get this:

How do I change things here?
{
  "version": "1.0",
  "session": {
    "new": false,
    "sessionId": "amzn1.echo-api.session.abeee1a7-aee0-41e6-8192-e6faaed9f5ef",
    "application": {
      "applicationId": "amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe" (not my application ID)
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.account.AM3B227HF3FAM1B261HK7FFM3A2" (not my user ID)
    }
  },
  "request": {
    "type": "SessionEndedRequest",
    "requestId": "amzn1.echo-api.request.d8c37cd6-0e1c-458e-8877-5bb4160bf1e1",
    "timestamp": "2015-05-13T12:34:56Z",
    "reason": "USER_INITIATED"
  }
}

**Comment by sushilks** [comment]
I haven't played much with the web-page based testing, I tried to trigger the intent on my setup and it appears to me that the application id was hardcoded. changing it on the web console did not have any effect. 
To test I think you can temporarily change the application id in the remote_conf.js file to match what is hardcoded "amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe"
let me know if that works.

**Comment by synack23** [comment]
Hi,

I was not able.to get the Web testing working.  Quick question about the
amazon app part, I use the test Web page to get the info for the slots and
utterance sections of the Amazon app, do I have to put anything in the
lambda part (and if so what)

**Comment by sushilks** [comment]
For configuring this on amazon, under "Skill information" tab and
"Endpoint" configuration select "HTTPS" instead of "Lambda ARN"
here you will need to provide an web address of the server that is
reachable from amazon.  i.e. https://myskill.ishere.com/somepath
Several folks have had difficulty with using IP address instead of FQDN.
Not sure if it's possible to use a IP address here.

**Comment by synack23** [comment]
ok, will try that. If I am running the server in terminal on my iMac what would I use as the somepath part of my web address (https://xxxx.ddns.net/??????)

**Comment by sushilks** [comment]
That's a bit of a long process, Basically plumbing is needed to allow
amazon services to be able to reach your iMac.
Depends on how your home network is setup there are multiple steps to doing
this

> You need to find out the external ip address of your home router,
> typically you can do this by going to "http://www.whatsmyip.org
> Then you will need to get a FQDN service to point to this ip address,
> there are some free services but you will need to figure out what service
> works best (LINK
> https://www.google.com/search?q=free+dynamic+dns&oq=free+dynamic+dns&aqs=chrome..69i57j69i64l2j69i60.3543j0j4&sourceid=chrome&es_sm=91&ie=UTF-8
> )
> Most home routers have NAT to prevent external attacks getting into your
> home, you will need to enable port forwarding on the NAT to forward
> external 443 port to your iMac.

I dont have an easy answer for this, wish there was one.

**Comment by synack23** [comment]
I got the port issue fixed, but now i'm getting an error from alexa Unable to resolve host name for the endpoint.  I am using ddns for my external IP.  Any ideas on how to fix this?

**Comment by sushilks** [comment]
Wow Lots of work needed to get it to work ... This needs to be a bit more friendly to do. 

Depending on where you got your DDNS from it may take time for it to be active, 
I would recommend testing that the DDNS translates to the right ip address by pinging it from some place outside of your home network, you can probably do it from work or use your phone's network to do it. 

It may also be an issue between Amazon and the DDNS provider, so you may need to change the DDNS provider. (This is unlikely)
Best of luck debugging. The sense of accomplishment when you get it to work will be very rewarding... :-)

**Comment by synack23** [comment]
I tried to connect with my phone and the connection was refused.  It was the correct IP by would not connect to port 443.  I have port forwarding turned on on my router so i'm kinda stuck.  I'm going to contact no ip support and see if they have any suggestions.

**Comment by sushilks** [comment]
Any update on this ?

**Comment by sushilks** [comment]
Will close this as there is no more activity. 
I am also guessing the problem was environment related.
