### ISSUE TITLE
Improper app id for test requests

### ISSUE THREAD

**Issue by chasepeeler** [sushilks/alexaHarmonyApp#20]
Requests generated by the test features on the /remote page submit a request with an app id other than the one specified in remote_conf.js, causing the server to return an error complaining about the an incorrect app id being provided.

**Comment by rgrdnr** [comment]
the amazon app id for the remote page is actually hard coded in the test.ejs file in the /view folder. 

editing the JSON on the webpage before submitting doesn't appear to work.  as a work around, check out '$scope.templates' json in that file and you can edit all the 'applicationId' values in the templates to match yours...

**Comment by sushilks** [comment]
A fix was easy enough, I have pushed it to the latest master. (Also verified it to work)
Feel free to re-open if the problem persists.
