### ISSUE TITLE
Connecting to Harmony Hub from AWS Lambda

### ISSUE THREAD

**Issue by dubsquared** [sushilks/alexaHarmonyApp#3]
Greetings, Sushil!

Thanks for your work on this code , it's been easy to get going for the most part, but I have ran into an issue I'm hoping you can help me with.

I intend on writing a blog post that details my how-to, as there doesn't seem to be any good documentation on how to get your code running in Lambda easily.

I've created my Alexa Skill using "remote" as my invocation command and created my Lambda function with all appropriate files (remote.js, remote_conf.js, node_modules, and package.json).  I have input my Alexa AppID and Harmony Hub IP (FQDN'd) in remote_conf.js.

I enabled the skill in the Echo app on my iPhone, and I can speak "Alexa, tell remote to turn everything off" or "Alexa, tell remote to mute."  I get a response back from Alexa saying the command is getting executed, and the Lamdba logs show the request and response going through with no problems.  I can also test the Skill in the Alexa Skills Builder and I am getting back the correct response.

The problem is, the command I am requesting is not happening in my home..  Everything is not turning off, nothing to getting muted, etc.  

Since it appears that everything is working with the code (I think), I figured it has to be something on my local network.   Here is what I have done:

I have setup port forwarding on my router in the following manner:

external IP : 5222 -> 192.168.11.40 : 5222 (ensured this was my HH by looking at DHCP leases and matching MAC to IP.  I then set a static IP for the HH to it'll always be .40 on my localnet).

Just as a test, I recently added this rules as well:
external IP : 80 -> 192.168.11.40 : 5222

Could you please provide your thoughts?  I've tried quite a bit of trial and error, but cannot get this to work.

Thanks in advance!

**Comment by sushilks** [comment]
In my case I was not running the code on lambda, I had a local server in my home (it was in the same L2 domain as the harmony hub) executing the code. 
From what I understand you are trying to run the code on lambda and are trying to pass the command via port forward to the harmony hub.  I am not sure what ports need to be forwarded.

To debug this out I have another utility that you can use to trigger commands on the hub(It can both read and write to the hub)
https://github.com/sushilks/harmonyHubCLI
you can use this within your L2 network and make sure that the hub is responding (Just run it from your laptop while connected to the home network where harmony is connected)
you can also use it from outside the home network and see if you can read/write form the hub.

Hope this will give you some help, if not post your findings.

**Comment by dubsquared** [comment]
I was getting the error when trying to run the harmonyCLI as referenced in https://github.com/sushilks/harmonyHubCLI/issues/1.  I was able to get that working with your workaround on xmpp-client version.

I can successfully change _activities_ now with the CLI on my home network via IP, and as well on the FQDN I setup.  I also tested the _devices_, and I can issue mute and change channel, etc.  All commands are executing with the CLI.

Still cannot get an activity change or device command to work via Alexa though.

**Comment by sushilks** [comment]
Not sure where the problems is coming from, there could be restriction on
Amazon side.
Are there any firewall rules on the lambda side.

**Comment by dubsquared** [comment]
Not that I can tell.  The only security groups are in the EC2 service, specifically.  

I was read this about the Hub protocol and getting a token from Logitech:  https://github.com/jterrace/pyharmony/blob/master/PROTOCOL.md

How, or is this getting handled anywhere in this code?  I'm about to take a look, but wanted to post here as well.

**Comment by sushilks** [comment]
I am not too familiar with that part of the code,  so post what you find.

One thing to consider is that there is no authentication on harmony api,
so if you open the port on public ip  any one can send it commands. It's
best to add a firewall on the public ip.

**Comment by dubsquared** [comment]
Yeah, that appears to be for the Logitech Link, not the HH.  I don't think it's an auth issue.  I did find that Lambda cannot bind to a port...not sure what the incoming request looks like coming from AWS.  Might need to run a tcpdump and see if anything shows.

**Comment by sushilks** [comment]
@dubsquared  Any updates on this ?

**Comment by sushilks** [comment]
Closing as there is no more updates.

**Comment by mmaceachran** [comment]
I am having the same problem.  I did find this on SO,  and it may be just timing out before the initialization is complete.

http://stackoverflow.com/questions/28449363/why-is-this-http-request-not-working-on-aws-lambda
