### ISSUE TITLE
Configurable Channels That Wait for Activities

### ISSUE THREAD

**Issue by rgauss** [sushilks/alexaHarmonyApp#8]
As a really lazy Amazon Echo user, I want to be able to simply ask for a particular channel to watch/listen to so that I can issue a single verbal command without having to know or consider the current state of my components or activities.

For example, with all components powered off I would like to simply say:

> Alexa, tell remote to watch TBS

and have the app know that the 'Watch Tivo' activity should be triggered, wait for that activity, then change to the appropriate channel.  If the 'Watch Tivo' activity is already active then just change to the appropriate channel.

The channels should be easily configured, i.e. in `remote_conf.js`.

Pull request coming shortly.

**Comment by sushilks** [comment]
Thanks for the code, This is going to be my default way to startup the tv .. :+1:
